on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A simple test
    steps:
      - uses: actions/checkout@v2
      - uses: emiliopedrollo/auto-merge@v1.2.0
        with:
          github_token: ${{ github.token }}
          target_branch: 'dev'
          allow_fast_forward: true
